### PR TITLE
Rebased and applied only RTS changes

### PR DESCRIPTION
**Pull request by develroo**
As I have used this myself, I took images of how I set it up with arbitrary tokens as light sources and how I named them associated with the area they light up. If the area it too large for one light, I usually append a suffix like Light-A10a

It is effective and gives the players a good idea of where they have explored and the point they need to go back to if they leave a map and come back to it later.

I hope the images help explain the text better but all feedback is welcome.

### CODE REVIEW

**Comment by Kruptein** [comment]
You should now be able to see the deploy logs to see what went wrong

**Comment by develroo** [comment]
Ugg. it does not like underscores in names. :roll_eyes: 

Oh well I will have to change that then. Give it an hour or so.

**Comment by Kruptein** [comment]
That is not the issue.

image
this is, one of your relative paths is wrong

**Comment by develroo** [comment]
Weird as the wall guide had them but oh well.

**Comment by develroo** [comment]
Ok seems to pass now. Thoughts? Does it look ok?

**Comment by Kruptein** [comment]
it mostly reminds me that I should look into proper rts/fow support :D

**Pull request merged**
